name: Build UnityModManager

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: if you host Unity DLLs in a separate private repo or storage, pull them here
      # - name: Download Unity DLLs
      #   run: ...

      - name: Build with MSBuild
        run: |
          msbuild UnityModManager/UnityModManager.csproj `
            /p:Configuration=Release `
            /p:PlatformTarget=AnyCPU
